### ISSUE TITLE
Can we hold on 3.0?

### ISSUE THREAD

**Issue by konklone** [benbalter/site-inspector#63]
There are still HTTPS test regressions from 1.x to 2.x I'd like to see resolved.

**Comment by konklone** [comment]
(Sorry for lack of detail - I'm traveling on my phone. Will give some more details when I can sit down.)

**Comment by benbalter** [comment]
Wanted to release a new version since there were 70+ commits on master, and 2.0.0 was released 3 months ago. [3.0.0](https://github.com/benbalter/site-inspector/releases/tag/v3.0.0) would have been 2.1 except a breaking change was introduced to the Sniffer API, returning a symbol, instead of a hash (and expanding the scope from CMSs to frameworks). 

Opened https://github.com/benbalter/site-inspector/issues/60 to track the boogyman regressions. Have discovered one that's awaiting your input. Specific regressions called out there, pull requests, or individual issues for other regressions are likely the best way to move forward and see them resolved. :smile_cat:
